name: vid-stab
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - cairo=1.16.0
  - certifi=2021.5.30
  - cycler=0.10.0
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.0
  - gmp=6.2.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - harfbuzz=2.4.0
  - hdf5=1.10.6
  - icu=67.1
  - jasper=1.900.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.12
  - libopencv=4.4.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - lz4-c=1.9.2
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - ncurses=6.2
  - nettle=3.4.1
  - numpy=1.21.0
  - opencv=4.4.0
  - openh264=2.1.1
  - openssl=1.1.1k
  - pcre=8.44
  - pip=21.1.3
  - pixman=0.38.0
  - py-opencv=4.4.0
  - pyparsing=2.4.7
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.61.2
  - wheel=0.36.2
  - x264=1!152.20180806
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
